version: '3.4'

networks:
  juniorstart-dev:
    driver: bridge
    
services:
  JuniorStart:
    image: juniorstart:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=juniorstartdb;username=admin;password=admin"
    networks:
      - juniorstart-dev
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "juniorstartdb"
    networks:
      - juniorstart-dev
volumes:
  db_volume: