version: '3.7'

services:
  api:
    container_name: 'junior_api'
    image: 'junior_api'
    build:
      context: .
      dockerfile: 'api.Dockerfile'
    links:
      - 'db'
    extra_hosts:
      - "junior_db:172.17.0.1"
    ports:
      - '5001:80'
    depends_on:
      - 'db'
  db:
    container_name: 'junior_db'
    image: "junior_db"
    build:
      context: .
      dockerfile: "db.Dockerfile"
    ports:
      - '5432:5432'   